const loadingTypes = {
  LOAD_PRODUCT_DATA: "LOAD_PRODUCT_DATA",
  LOAD_NEW_MEN_PRODUCTS: "LOAD_NEW_MEN_PRODUCTS",
  LOAD_NEW_WOMEN_PRODUCTS: "LOAD_NEW_WOMEN_PRODUCTS",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_ORDER_HISTORY: "LOAD_ORDER_HISTORY",
  LOAD_ORDER_DETAILS: "LOAD_ORDER_DETAILS",
  LOAD_HERO: "LOAD_HERO",
};

export default loadingTypes;
